# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 15:46 then edited by hand in order
# to set the content type of the answers.
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    """ Manually update the content type for django Polymorphic """
    answer_base = apps.get_model('survey', 'AnswerBase')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    new_ct = ContentType.objects.get_for_model(answer_base)
    answer_base.objects.filter(
        polymorphic_ctype__isnull=True
    ).update(polymorphic_ctype=new_ct)


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('survey', '0003_auto_20170320_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerbase',
            name='polymorphic_ctype',
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='polymorphic_survey.answerbase_set+',
                to='contenttypes.ContentType'),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
